version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./site:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./php
    volumes:
      - ./site:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: